### ISSUE TITLE
`Bounds out of range` while parsing ASRock A520M HVS 1.31 firmware 

### ISSUE THREAD

**Issue by cwerling** [fiedka/fiedka#50]
as discussed @orangecms 

```
panic: runtime error: slice bounds out of range [:8796093022208] with capacity 9821616
wasm_exec.js?5580:56 
wasm_exec.js?5580:56 goroutine 6 [running]:
wasm_exec.js?5580:56 github.com/linuxboot/fiano/pkg/uefi.NewFirmwareVolume({0x12a2250, 0x95ddb0, 0x95ddb0}, 0x6a2250, 0x0)
wasm_exec.js?5580:56 	/Users/cwerling/Git/fiedka/pkg/mod/github.com/linuxboot/fiano@v5.0.0+incompatible/pkg/uefi/firmwarevolume.go:257 +0x7b
wasm_exec.js?5580:56 github.com/linuxboot/fiano/pkg/uefi.NewBIOSRegion({0xc00000, 0x1000000, 0x1000000}, 0x0, 0x0)
wasm_exec.js?5580:56 	/Users/cwerling/Git/fiedka/pkg/mod/github.com/linuxboot/fiano@v5.0.0+incompatible/pkg/uefi/biosregion.go:115 +0x35
wasm_exec.js?5580:56 github.com/linuxboot/fiano/pkg/uefi.Parse({0xc00000, 0x1000000, 0x1000000})
wasm_exec.js?5580:56 	/Users/cwerling/Git/fiedka/pkg/mod/github.com/linuxboot/fiano@v5.0.0+incompatible/pkg/uefi/uefi.go:153 +0x4
wasm_exec.js?5580:56 main.utka({{}, 0x0, 0x0}, {0x4244e0, 0x2, 0x3})
wasm_exec.js?5580:56 	/Users/cwerling/Git/fiedka/src/main.go:55 +0x10
wasm_exec.js?5580:56 github.com/happybeing/webpack-golang-wasm-async-loader/gobridge.registrationWrapper.func1({{}, 0x0, 0x0}, {0x4244e0, 0x3, 0x3})
wasm_exec.js?5580:56 	/Users/cwerling/Git/fiedka/pkg/mod/github.com/happybeing/webpack-golang-wasm-async-loader/gobridge@v0.0.0-20201126150039-3d18007626dd/gobridge.go:19 +0x5
wasm_exec.js?5580:56 syscall/js.handleEvent()
wasm_exec.js?5580:56 	/usr/local/Cellar/go/1.17.2/libexec/src/syscall/js/func.go:96 +0x27
```

macOS 11.3, npm 8.10, fiedka 5520b99680641f1127e4ed49f9e277bf1625b7ea

**Comment by cwerling** [comment]
NB: Exception only occurs when an image is taken from a live system. The original file from ASRock is parsed just fine.

**Comment by orangecms** [comment]
It looks like due to Go tooling shenanigans we had pulled a somewhat old version into Fiedka back then.
All should be okay now. I couldn't see this issue anywhere.
